version: "3.8"

services:

  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    ports:
      - "3001:3001"

  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - "3000:3000"
    depends_on:
      - inventory-service